### ISSUE TITLE
.NET Standard 2.0 support?

### ISSUE THREAD

**Issue by fubar-coder** [craigbridges/Nettle#4]
Hi,

do you have .NET Standard 2.0 support on your roadmap?

Kind regards,
Mark

**Comment by craigbridges** [comment]
Hi Mark,

Yes, I would definitely like to add support for .NET Standard 2.0 at some point. I'm not sure when I will get time to do it at the moment because I'm heavily tied up with other projects. 

I haven't actually used .NET Standard 2.0 yet or upgraded any projects to it, so I'm unsure of any problems I might face. That's why I have put off doing it for now.

If you would like to add support sooner than later, feel free to create a fork, make the modifications and then create a pull request. Alternatively, if you have experience with compatibility/API support problems faced - feel free to share!

Thanks for your interest in Nettle!

Craig

**Comment by craigbridges** [comment]
Hi Mark,

Nettle has now been ported to .NET Standard 2.0! I haven't released it on NuGet yet as I need to do lot's of testing to make sure everything works fine still.

The latest changes have been pushed to master so it's all available to pull.

Craig
